### ISSUE TITLE
Refactor tests?

### ISSUE THREAD

**Issue by shadowspawn** [pkgjs/parseargs#105]
Will we be copying tests from this repo again?

Based on the [PR](https://github.com/nodejs/node/pull/42675/files) to [nodejs/node](https://github.com/nodejs/node), it looks like it would make sense to have all the tests in a single file. 
And `.mjs`. 
And switch test library or add a wrapper so can cut-and-paste:

```
// node
assert.deepStrictEqual(args, expected);
```

```
// here
t.deepEqual(args, expected);
t.end();
```

**Comment by bcoe** [comment]
👍 would be nice to eliminate the manual replacing I'm doing to match Node's test runner.
