### ISSUE TITLE
docs: add strict:false example to upstream ?

### ISSUE THREAD

**Issue by shadowspawn** [pkgjs/parseargs#114]
The upstream docs do not include an example of zero-config parsing, with strict:false. Want one?

It was a big part of the initial design, we were considering shipping without strict! Although the current contributors are all strict-friendly. 👮 

This could mention explicitly that most error checking in `strict:false` is left to the author. 😅

**Comment by shadowspawn** [comment]
Also, no worries if want to focus on the functional changes first and catch up with improvements to the documentation later.

**Comment by bcoe** [comment]
@shadowspawn my preference would be to land an MVP, and then follow up immediately with smaller improvements.

There have been 217 points of feedback on the PR against Node so far, too many more and I think there's a danger my computer gets thrown off the back patio :stuck_out_tongue:

**Comment by shadowspawn** [comment]
Didn't get any interest in this and/or subsequent comments from users. Closing.
