### ISSUE TITLE
Examples all use special case of repeated option

### ISSUE THREAD

**Issue by shadowspawn** [pkgjs/parseargs#14]
The examples all use a special case of a repeated option in the command line: https://github.com/pkgjs/parseargs#-examples-w-output

```
const argv = ['-f', '--foo=a', '--foo', 'b']
```

I suggest a repeated option should be in a separate example and not occur in examples showing other behaviours.

It is clever seeing the behaviour change for a single command-line as the `parseArgs` configuration is changed, but I think it detracts from the clarity of the examples of (other) specific behaviours.

(In particular the reader has to deduce or understand the behaviour of a repeated option in every example. Repeated options have multiple possible implementations, and `parseArg` behaviour was modified from count to last-one-wins due to feedback in the Initial Proposal, with implicit array also being suggested and discussed!)

**Comment by bcoe** [comment]
@shadowspawn I agree with this feedback 👍 want to send a patch?

**Comment by shadowspawn** [comment]
Fixed by #23
