### ISSUE TITLE
parseArgs in runtimes where `global` is not defined

### ISSUE THREAD

**Issue by kisaragi-hiu** [pkgjs/parseargs#157]
This module is useful as a polyfill for older Node versions. But it could also be useful for other runtimes, such as [gjs](https://gitlab.gnome.org/GNOME/gjs), that may not want to implement a Node compatibility layer but nevertheless would find a good argument parser helpful.

Right now this module appears to polyfill a bunch of Node internal functions by modifying `global` (such as in [internal/primordials.js](https://github.com/pkgjs/parseargs/blob/main/internal/primordials.js)). This is fine, even preferrable, when it was to be included in Node, but as a standalone library this has two problems:

1. This pollutes the global namespace, which is inappropriate in non-Node contexts. A hypothetical case is someone wanting to emulate command parsing in the browser and utilizing this library - which works, but their namespace is now polluted.
2. This doesn't work in some runtimes. Some runtimes do not have `global` (generally they have `globalThis` though), so the modification of `global` means this library just doesn't work there, even though it could.

   My actual use case is that I'm making a command line program with [gjs](https://gitlab.gnome.org/GNOME/gjs) (to make use of [GLib](https://gitlab.gnome.org/GNOME/glib)). `parseArgs({args: ARGV, options: {...}})` would work wonders there, but the polyfilling behavior prevents it from working. (`ARGV` is gjs's equivelant to `process.argv.slice(2)`)

   Runtimes that have some use and don't have `global`:
   - gjs: has `globalThis` instead
   - duktape [(online REPL)](https://duktape.org/dukweb#print(%22hello%22)%3B%0Atry%20%7B%0Aprint('The%20global%20object%20is%20'%20%2B%20global)%3B%0A%7D%20catch%20(e)%20%7B%0Aprint(e)%0A%7D): has `globalThis` instead
   - QuickJS [(online REPL based on QuickJS)](http://numcalc.com/): has `globalThis` instead

This can be fixed by either:

- Moving away from being a polyfill (which, granted, is quite a big change to make), or
- Falling back to `globalThis` if `global` doesn't exist.

**Comment by kisaragi-hiu** [comment]
Since [globalThis was added in Node 12](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/globalThis#browser_compatibility) and this package [requires Node 14+](https://github.com/pkgjs/parseargs/blob/main/package.json#L6), and since internal/primordials.js even already [depends on `globalThis` existing](https://github.com/pkgjs/parseargs/blob/d2f6c870d764824a08b3da673a00b68e54a33202/internal/primordials.js#L171), [internal/primordials.js](https://github.com/pkgjs/parseargs/blob/main/internal/primordials.js) could just be patched to always use `globalThis`. This wouldn't solve the namespace pollution, but it does make this library work on gjs.

**Comment by shadowspawn** [comment]
> Right now this module appears to polyfill a bunch of Node internal functions...

Historical note: this was to make it easy for submitting `parseArgs` to node, rather than a fully-functional polyfill of those internals.

**Comment by ljharb** [comment]
although a non-broken browser bundler must always transform global into window, it’s fine to change it to use globalThis for server runtimes, given our engines declaration.
