### ISSUE TITLE
Transfer iansu/eslint-plugin-node-core to pkgjs org

### ISSUE THREAD

**Issue by iansu** [pkgjs/parseargs#17]
I extracted the ESLint config used by Node core into a standalone package here: https://github.com/iansu/eslint-plugin-node-core. The idea is that we can use this config in projects like parseargs to make the eventual porting of the code into Node core as easy as possible.

We would like to transfer this repo from my GitHub account into the pkgjs org. I think I will need permission to create repos in pkgjs to do this. I would also like the ability to publish `@pkgjs/eslint-plugin-node-core` to npm.

**Comment by darcyclarke** [comment]
I don't have owner/admin access for this org here on GitHub (will need @wesleytodd / @mhdawson to help there) but I have invited [`@iansu`](https://www.npmjs.com/~iansu) to the `pkgjs` org on npmjs.com. Let me know if you have any issues pushing up a new scoped package @iansu.

**Comment by mhdawson** [comment]
It's on my list to take a look at this to understand what needs to get done, but have not quite yet been able to. Hope be able to do that some time this week.

**Comment by mhdawson** [comment]
@iansu could you create an issue in the nodejs/package-maintenance repo with the request as outline here:https://github.com/nodejs/package-maintenance/blob/main/Governance.md#adding-or-removing-repositories

Could you also add the standard boilerplate files, (LICENSE, CONTRIBUTING.md, CODE_OF_CONDUCT.md, you can see the pkgjs/support repo for examples). 

After the request and 72 hours (assuming no objections) then I can move over the repo if you give me access to your repo.

I can then set up the team so you can manage the new repo.

In terms of publishing the npm I think you are already in the group/team in the org that should let you do that.

**Comment by iansu** [comment]
Thanks @mhdawson. I will take care of that this weekend.

**Comment by iansu** [comment]
It looks like this is actually going to be maintained in the Node.js org so I'm going to archive my version instead of transferring it to the pkgjs org.

https://github.com/nodejs/eslint-plugin-nodejs-internal
