### ISSUE TITLE
Add support for short option groups

### ISSUE THREAD

**Issue by bcoe** [pkgjs/parseargs#2]
In the FAQ it's mentioned that one of the blockers for short options is `-foo` being treated the same as `--foo`. I'd argue that I'd rather people not be able to set `-foo`, but that someone can write the command:

`rm -rf`, or `git -rf ./node_modules`.

_tldr; I think people know long form arguments take two dashes, and it was a mistake to in yargs/yargs-parser to allow for -foo._

Refs: #1

**Comment by ljharb** [comment]
I agree it was a mistake if `-foo` can mean anything different than `-f -o -o`.

**Comment by joesepi** [comment]
I think we agree to support short options.

**Comment by shadowspawn** [comment]
> I agree it was a mistake if `-foo` can mean anything different than `-f -o -o`.

I agree in the unconfigured case, where `f`  and `o` implicitly do not take a value.

To expand though, if option `f` takes a value then the POSIX specification is that `f` will get the value `oo`. This is something which could be done in `parseargs` if `f` is specified in `withValue`

References for POSIX and GNU extensions:
- https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap12.html
- https://pubs.opengroup.org/onlinepubs/9699919799/xrat/V4_xbd_chap12.html
- https://www.gnu.org/prep/standards/html_node/Command_002dLine-Interfaces.html

**Comment by ljharb** [comment]
Ok, fair enough that `-f oo` is a legit value for that as well :-)

**Comment by bcoe** [comment]
> To expand though, if option f takes a value then the POSIX specification is that f will get the value oo. This is something which could be done by parseArgs if f is specified in withValue

Seems like if you've explicitly configured `f` to take a value, it wouldn't be too hard to desing the parser to accept `-foo` and `-f oo`. Perhaps start with the simple behavior of assuming a single dash indicates a series of flags, but consider extending it to support this behavior.

**Comment by bnb** [comment]
> I agree it was a mistake if -foo can mean anything different than -f -o -o.

I agree with this. I also think it would be nice if we can allow people to yeet out of this rule if they _really_ want to for their own reasons (the most obvious being legacy commands that are moving to this functionality).

**Comment by shadowspawn** [comment]
My order of priorities for short options is plain arg (i.e. single dash followed by single character) working fully, and then short option groups for option flags, and then option with value following in argument (for `withValue`). And last, opting out of anything except plain short options.

Interested in working on this, but happy to leave it for someone else. Don't want to hog all the coding fun. 😄
