### ISSUE TITLE
What is our linter preference

### ISSUE THREAD

**Issue by joesepi** [pkgjs/parseargs#3]
See: https://github.com/pkgjs/parseargs/pull/1#discussion_r615043617

**Comment by joesepi** [comment]
It would be nice to get as close to `nodejs/node` as possible.

**Comment by joesepi** [comment]
For reference: https://github.com/nodejs/node/blob/master/.eslintrc.js

**Comment by ljharb** [comment]
I don't think that should be a goal; node's linter settings are often exceedingly unidiomatic for the ecosystem.

**Comment by ljharb** [comment]
Imo prettier, if used, should only be used via eslint config :-)

I think that its an impractical mandate for the reason you mention, but a shared config is a good idea for common patterns.

The most common idiom in the ecosystem, by any metric, is the Airbnb config combined with prettier’s config. Is there a reason not to just use those?

**Comment by targos** [comment]
I don't think the `nodejs/node` config should be replicated/copied to other projects. It is a result the history of the project and has a lot of special rules that are there only to avoid big changes to the code base.

**Comment by mhdawson** [comment]
for https://github.com/pkgjs/support I used eslint with semistandard - https://github.com/pkgjs/support/blob/main/.eslintrc.json
