### ISSUE TITLE
Paranoia with Primordials

### ISSUE THREAD

**Issue by shadowspawn** [pkgjs/parseargs#31]
@ljharb commented in #26 
> We should probably try to keep this package robust, primordials-style.

I punted and said could we raise a separate issue for that... and here it is!

So, from a state of ignorance, I'll raise some questions:
1) should we use primordials?
2) is there a convenient way to make primordials available to current repo code?

-----

I have no experience with the node internals or primordials. I did a quick search for primordials and found:
- https://github.com/nodejs/node/issues/30697
-  https://github.com/nodejs/node/blob/141a6e34eed05577edf43ad085a74f330d0559cb/lib/internal/per_context/primordials.js#L5-L7

**Comment by ljharb** [comment]
We don’t have to use node’s actual primordials facility here - but it’d be easy to migrate to it later if we module-level-cached builtins that were call-bound.

Meaning:
```
const callBound = require('call-bind/callBound');
const slice = callBound('Array.prototype.slice');

/* and later */
slice(arr)
```

**Comment by shadowspawn** [comment]
First draft of primordials done in #37, with another PR coming to generalise the support in a reusable way for other polyfill proofs of concept projects: https://github.com/pkgjs/parseargs/pull/37#issuecomment-1013919084

**Comment by shadowspawn** [comment]
Closing this as we have added and are using `primordials.js` to allow writing code that will slot into the node environment, which is the main goal.

If we want a robust package for use stand-alone, more work to do.

**Comment by shadowspawn** [comment]
Adding a link to the documentation: https://github.com/nodejs/node/blob/main/doc/contributing/primordials.md
