### ISSUE TITLE
How to handle other environments like Electron

### ISSUE THREAD

**Issue by joesepi** [pkgjs/parseargs#5]
See: https://github.com/pkgjs/parseargs/pull/1#discussion_r615040966

**Comment by joesepi** [comment]
In the latest meeting, @darcyclarke said @ruyadorno may have some work done on this bit ("main args")

**Comment by joesepi** [comment]
It would perhaps make sense to just pull in what `yargs` does as @bcoe had pointed out in the original comment. See that implementation here:
https://github.com/yargs/yargs/blob/master/lib/utils/process-argv.ts

**Comment by shadowspawn** [comment]
For interest, Commander issues for other environments:
- Electron feedback from > 10 users (including likes)
     - https://github.com/tj/commander.js/issues/512
- zx feedback from 1 user
    - https://github.com/tj/commander.js/issues/1592

**Comment by shadowspawn** [comment]
Moved forward status quo in #20
