### ISSUE TITLE
make it possible to require long options with values use `=`

### ISSUE THREAD

**Issue by ljharb** [pkgjs/parseargs#52]
Per discussion around https://github.com/pkgjs/parseargs/issues/25#issuecomment-1023492686, I want to use this API, but enforce that options with values use an `=` sign.

It's fine if the validation code is in userland (ie, my code) on top of parseArgs.

How can I do that?

**Comment by shadowspawn** [comment]
There is information available to the author in the setup of the parsing configuration, in addition to the `parseArgs` results.

Possible approach, with bonus support for `--`:

```js
const allArgs = process.argv;
const withValue = ['foo'];

const dashdash = allArgs.indexOf('--');
const possibleOptions = (dashdash >= 0) ? allArgs.slice(0, dashdash) : allArgs;

withValue.forEach((option) => {
    if (possibleOptions.includes(`--${option}`)) {
        console.error(`--${option} must have a value specified using "=", like "--${option}=value"`);
        process.exit(2);
    }
})

parseArgs(allArgs, { withValue });
```

**Comment by ljharb** [comment]
imo I think that having to look at `process.argv` is a failure of parseArgs.

**Comment by shadowspawn** [comment]
I have some empathy with your reaction. But there are only going to be nice answers to some changes and additions to the `parseArgs` base behaviour. 

I think the "Intended Audience" from the previous proposal was quite realistic in this regard. https://github.com/pkgjs/parseargs/issues/45#issuecomment-1020817921

There are other parsing decisions which are not represented in the results, and an author can not always change the rules by looking at the results. For example, an author wanting to make it an error if an option is specified more than once. `parseArgs` will silently return the second usage. 

A different case that came up recently in context of `parseArgs` was `npm` allows `-ws` as a shortcut for `--workspace`. The wisdom of this is debatable, but it is a nice example for something more elegantly done _before_ calling `parseArgs`. Making the substitution before parsing avoids `-ws` triggering short option groups, and gets the full support in parsing for `withValue` and `multiples` for `--workspace`.

**Comment by shadowspawn** [comment]
Another possible approach, `parseArgs` does the parsing and bring-your-own validation.

```js
const myValues = ['foo'];
const myFlags = ['flag'];

// Do not declare any withValue since do not want to allow "--foo value"
const { options, values } = parseArgs();

// Bring your own validation
Object.keys(options).forEach((option) => {
    if (myFlags.includes(option)) {
        if (values[option] !== undefined) {
            console.error(`Unexpected value for option: ${option}`);
        }
    }
    else if (myValues.includes(option)) {
        if (values[option] === undefined) {
            console.error(`Missing value for option: ${option}`);
        }
    } else {
        console.error(`Unknown option: ${option}`);
    }
});
```

**Comment by bcoe** [comment]
As with #45, I'm a bit worried about feature creep ... `yargs`, and probably `commander` too?, ended up with [dozens of configuration options](https://github.com/yargs/yargs-parser#configuration) to support people's various personal preferences for command line parsing. I'd like to side step this in Node core, by sticking to the message:

```
It is already possible to build great arg parsing modules on top of what Node.js provides; the prickly API is abstracted away by these modules. Thus, process.parseArgs() is not necessarily intended for library authors; it is intended for developers of simple CLI tools, ad-hoc scripts, deployed Node.js applications, and learning materials.

It is exceedingly difficult to provide an API which would both be friendly to these Node.js users while being extensible enough for libraries to build upon. We chose to prioritize these use cases because these are currently not well-served by Node.js' API.
```

I agree that if we could come up with a reasonable hook for "bringing your own validation", perhaps we could both keep the API surface really small, while supporting various preferences.

**Comment by bakkot** [comment]
> I agree that if we could come up with a reasonable hook for "bringing your own validation"

To throw out an option I've used before in other parsing libraries: if the parsed object surfaces (or can be made to surface) location information, that makes it easy for a consumer to do this sort of check. For example, imagine that there's a `indices` property (name obviously tbd) which gives a map from each option to the indexes in `argv` which contributed to that option:

```js
const { flags, values, positionals, indices } = parseArgs(argv, { withValue, ... });
for (let option of withValue) {
  for (let index of indices[option] ?? []) {
    if (!argv[index].includes('=')) {
      console.error(`--${option} must have a value specified using "=", like "--${option}=value"`);
      process.exit(2);
    }
  }
}
```

It also makes it possible to build many other sorts of validation, like "was this flag duplicated" (check to see if `indexes[flag].length > 1`), or "option A must be specified before option B" (just compare their indexes).

---

(It might be better for `indexes` to be a _tiny_ bit richer than I've described it here, since as described you can't tell without re-parsing if a given index was `--arg=value`, `--arg`, or `value`. So perhaps `{ index, kind }` pairs would be better than just the raw number.)

**Comment by shadowspawn** [comment]
Interesting idea. I like your examples of situations that this can detect: duplicate options, ordered options. What parsing libraries offer this, or is this something you added yourself? 

However, I'm only exploring. I don't think exposing more information is important at this time!

**Comment by bakkot** [comment]
> What parsing libraries offer this

No JS-based CLI argument parsers I'm aware of does this, to be clear, but parsers _in general_ almost always do. See pretty much every parser on [astexplorer.net](https://astexplorer.net/), for some examples.

**Comment by bcoe** [comment]
I like @bakkot's suggestion a lot. Another advantage of this design, is that errors can point to the exact token in process.argv that broke the parse, if we do opt for strict by default.

There's a standard parse format I've used before, uinst, https://www.npmjs.com/package/unist-util-visit. Which has the benefit of tooling behind it.

I agree with @shadowspawn, perhaps this is a post MVP addition, but can be a plan for how we expose highly customizable validation.

**Comment by shadowspawn** [comment]
For interest and can safely be ignored, I came across a mode in Minimist that could have led to confusion about long options and values. Minimist lets you switch zero-config from `withValue` to default flag (boolean), but only affects long flags. (Minimist is pretty cool, but is not a shining example of consistent UX behaviour...)

```js
var argv = require('minimist')(process.argv.slice(2));
console.log(argv);
```
```
% node boolean-true.js -a A --vv=VV --ww WW
{ _: [], a: 'A', vv: 'VV', ww: 'WW' }
```

```js
var argv = require('minimist')(process.argv.slice(2),  { boolean: true });
console.log(argv);
```
```
% node boolean-true.js -a A --vv=VV --ww WW
{ _: [ 'WW' ], a: 'A', vv: 'VV', ww: true }
```

**Comment by shadowspawn** [comment]
Support for more meta-data has been added in #129
Using the new meta-data to require that long option values are supplied with `=` is an example in #136
