### ISSUE TITLE
withValue requires '=' for value to be set.

### ISSUE THREAD

**Issue by bcoe** [pkgjs/parseargs#54]
```js
    const parse = parser(['--pow', 'xixxle'], {
      withValue: ['pow']
    })
```

Parses as:

```js
{
  flags: { pow: true },
  values: { pow: undefined },
  positionals: [ 'xixxle' ]
}
```

I believe this should be:

```js
{
  flags: { },
  values: { pow: 'xixxle' },
  positionals: [  ]
}
```

**Comment by shadowspawn** [comment]
Speculation: I will try reproducing later, but my first guess is that your shim is not passing through `withValue` successfully and you are getting zero-config behaviour.

**Comment by shadowspawn** [comment]
I am unable to reproduce the problem as described. I see this behaviour:

```js
const { parseArgs } = require('@pkgjs/parseargs');

const parsed = parseArgs(['--pow', 'xixxle'], {
    withValue: ['pow']
  })

console.log(parsed);
```

```
% node index.js 
{ flags: { pow: true }, values: { pow: 'xixxle' }, positionals: [] }
```

(Wondering why there is there an entry for `pow` in `flags`? See #38: the README and naming and code are not all in sync! The code is still using existence conventions. Looking forward to making a decision and getting things consistent.)

**Comment by bcoe** [comment]
@shadowspawn let me test again against the latest `main`, I wonder if it's a bug we merged a fix for.

**Comment by bcoe** [comment]
I was being silly and not passing the options to the parser.
