### ISSUE TITLE
should "--" signal an end to parsing?

### ISSUE THREAD

**Issue by bcoe** [pkgjs/parseargs#58]
Perhaps we should just put `--` in `_`, and an implementer could fallback to calling `slice` on `process.argv`, if they observe it?

**Comment by ljharb** [comment]
Yes, double dash should signal an end to parsing.

**Comment by shadowspawn** [comment]
I assume `_` is `positionals`. Not sure if you are wondering about ending the option processing, or about whether to include `--` in `positionals`. In any case, a short answer...

I am happy with the currently implemented behaviour, that the `--` is consumed and the remaining arguments are put into `positionals` (and not examined for options).

(I suggested README changes describing the current behaviour for `--` in abandoned #34.)

**Comment by bnb** [comment]
Yes, this is generally the DX I've seen in Node.js-based tooling.

**Comment by shadowspawn** [comment]
The current behaviour implemented in `parseArgs` is the same as in all the reference implementations from #76:

```
try-getopt-long % ./ex foo -- bar --option
non-option ARGV-elements: foo bar --option 

try-commander % node index.js foo -- bar --option
positionals: [ 'foo', 'bar', '--option' ]

try-yargs % node index.js foo -- bar --option
{ _: [ 'foo', 'bar', '--option' ], '$0': 'index.js' }

try-minimist % node index.js foo -- bar --option
{ _: [ 'foo', 'bar', '--option' ] }
```
