### ISSUE TITLE
What to do with 3 or more dashes

### ISSUE THREAD

**Issue by joesepi** [pkgjs/parseargs#7]
See: https://github.com/pkgjs/parseargs/pull/1#discussion_r615042345

See also near bottom of FAQs, design doc says:
>Is ---foo the same as --foo?
>- no
>- the first flag would be parsed as '-foo'
>- the second flag would be parsed as 'foo'

https://github.com/pkgjs/parseargs#faqs

**Comment by ljharb** [comment]
I would expect `---foo` to be the flag "-foo", or an error - ie, the third dash shouldn't change how things are parsed.

**Comment by joesepi** [comment]
If we want to avoid throwing errors, should we simply warn or info on such a case where more than 2 dashes are used?

**Comment by ljharb** [comment]
Do we want that?

**Comment by shadowspawn** [comment]
Closed by #21
