### ISSUE TITLE
Make `type` mandatory for configured options

### ISSUE THREAD

**Issue by bakkot** [pkgjs/parseargs#94]
@bcoe suggested this [here](https://github.com/pkgjs/parseargs/pull/74#discussion_r846689938). I'm in favor of it, and wanted to open an issue for it so it doesn't get lost.

This would definitely apply to `strict`. I don't know if it should also apply to non-strict. I'm still not entirely clear on what non-strict is _for_, which makes it hard to judge what's right for it.

I note that if if `type` is not required for non-strict, you have odd cases like

```js
parseArgs({ options: { foo: { multiple: true } }, args: ['--foo', 'a', '--foo'] })
```
where... would that give you `{ values: { foo: ['a', true] } }`, or what?

**Comment by shadowspawn** [comment]
> I don't know if it should also apply to non-strict. 

I think it applies for both strict and non-strict.

**Comment by shadowspawn** [comment]
Per the original comment, the idea is to make the empty configuration option illegal.

Implicit boolean type, no clues:
```js
parseArgs({
  options: {
    foo: {},
  },
});
```

Explicit:
```js
parseArgs({
  options: {
    foo: { type: 'boolean' },
  },
});
```
